### ISSUE TITLE
App.js default unit test fails

### ISSUE THREAD

**Issue by PreciseAsteroid** [the-road-to-learn-react/the-road-to-learn-react#24]
The default test with jest fails. log below.
My guess is that is related to the fact that the App component fires http requests that returns a promise and that the default test does not handle.

`TypeError: Network request failed
        at XMLHttpRequest.xhr.onerror (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/whatwg-fetch/fetch.js:408:16)
        at XMLHttpRequest.callback.(anonymous function) (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:289:32)
        at invokeEventListeners (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
        at invokeInlineListeners (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:166:7)
        at EventTargetImpl._dispatch (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:122:7)
        at EventTargetImpl.dispatchEvent (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
        at XMLHttpRequest.dispatchEvent (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
        at XMLHttpRequest.abort (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:384:16)
        at Object.abort (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:315:13)
        at RequestManager.close (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:145:21)
        at Window.close (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/jsdom/lib/jsdom/browser/Window.js:316:29)
        at JSDOMEnvironment.dispose (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/jest-environment-jsdom/build/index.js:46:19)
        at Promise.resolve.then (/Users/cookies/Documents/programming/learnreact/hackernews/node_modules/jest/node_modules/jest-cli/build/runTest.js:65:9)`

**Comment by rwieruch** [comment]
@PreciseAsteroid When do the tests fail? Right after you implemented them in chapter 3 or at the end of the book?

**Comment by rwieruch** [comment]
As a reference: https://github.com/rwieruch/hackernews-client

**Comment by dudko** [comment]
I can confirm this issue. In order to reproduce it, just `git checkout 393ce5a` in referenced repo and `npm run test`.

**Comment by rwieruch** [comment]
@dudko thanks! I will check it. Can you confirm that it fails because of the http requests?

**Comment by dudko** [comment]
I don't know. I was trying to figure it out on my own, but without result. Tests are passing, just exception is thrown.

**Comment by rwieruch** [comment]
I will double check it in the next edition of the book. Thanks for your report on this! Really appreciate it @dudko @PreciseAsteroid

**Comment by Fenwick17** [comment]
Is there an update for this which will allow me to progress? Currently can't run the default unit test or anything after that.

**Comment by rwieruch** [comment]
Can you verify if this hot fix by @devserkan would work @Fenwick17 ? https://github.com/rwieruch/hackernews-client/issues/2 I have it already on my list for the next edition (see https://github.com/rwieruch/the-road-to-learn-react/issues/52).

**Comment by Fenwick17** [comment]
Have just tested this out with the default test and it does pass. I will continue with the book creating custom tests, and report back. 
It is worth noting the versions I am using:
Node - v8.1.2
Yarn - 0.21.3
NPM - 5.0.3

**Comment by rwieruch** [comment]
Perfect. Thank your very much for providing the feedback! 👍
