### ISSUE TITLE
Problem with 'ref a dom element' example when testing ?

### ISSUE THREAD

**Issue by shearichard** [the-road-to-learn-react/the-road-to-learn-react#90]
## Summary
When following the "Ref a DOM Element" section I found that my code would run perfectly well (and move the focus to the search box as intended) when running the server but would crash and burn when attempting to run tests.

## Nature of fault

When running the tests I got this stack trace 

```
    TypeError: Cannot read property 'focus' of undefined

      at Search.componentDidMount (src/App.js:54:8)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:8798:24)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:9967:9)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:540:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:579:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:436:27)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:10071:9)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:11003:42)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:10952:7)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:10861:7)
      at scheduleWorkImpl (node_modules/react-dom/cjs/react-dom.development.js:10744:11)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:10706:12)
      at scheduleTopLevelUpdate (node_modules/react-dom/cjs/react-dom.development.js:11177:5)
      at Object.updateContainer (node_modules/react-dom/cjs/react-dom.development.js:11215:7)
      at node_modules/react-dom/cjs/react-dom.development.js:15232:19
      at Object.unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:11086:12)
      at renderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:15231:17)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:10861:7)
      at scheduleWorkImpl (node_modules/react-dom/cjs/react-dom.development.js:10744:11)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:10706:12)
      at scheduleTopLevelUpdate (node_modules/react-dom/cjs/react-dom.development.js:11177:5)
      at Object.updateContainer (node_modules/react-dom/cjs/react-dom.development.js:11215:7)
      at node_modules/react-dom/cjs/react-dom.development.js:15232:19
      at Object.unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:11086:12)
      at renderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:15231:17)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:15296:12)
      at Object.it (src/App.test.js:28:24)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

The code being referenced at the top of the stack (src/App.js:54:8) looks like this 

```
componentDidMount() {
this.input.focus();
}
```

In addition to that (and other similar) stack traces the following rather opaque error messages were shown below the test summary 

```
  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5533
    The above error occurred in the <Search> component:
        in Search (at App.js:239)
        in div (at App.js:238)
        in div (at App.js:237)
        in App (at App.test.js:19)

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```
... and ...
```
  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5533
    The above error occurred in the <Search> component:
        in Search (at App.test.js:37)

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

## Resolution
I rewrote the relevant code as follows 
```
  componentDidMount() {
    if(this.input) {
      this.input.focus();
    };
```
and that resolves the issue in test while allowing the server to run as intended.

## Suggestion
Should the example code be altered to adopt the usage shown above ?

**Comment by rwieruch** [comment]
Thanks for reporting this issue! If the condition would already solve it, it would be great to see a small PR for it. Would you mind creating one for the issue :)
